/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: e7e51fdcc36e3cb8b66c28cc7e6b1a45)
interface __BaseEnv_Env {
  AI: Ai;
  AUTH_IDENTITY_ADAPTER: string;
  WORKOS_CLIENT_ID: string;
  WORKOS_API_KEY: string;
  WORKOS_COOKIE_PASSWORD: string;
  ThinkAgent: DurableObjectNamespace<import("./src/server").ThinkAgent>;
  AgentIdentityStore: DurableObjectNamespace<import("./src/server").AgentIdentityStoreDO>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ThinkAgent" | "AgentIdentityStoreDO";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      "AUTH_IDENTITY_ADAPTER" | "WORKOS_CLIENT_ID" | "WORKOS_API_KEY" | "WORKOS_COOKIE_PASSWORD"
    >
  > {}
}
